

export const Revenue = () =>{

  var arraylist = [
    {head:"Publisher Advance payment",
    rev:"$ 0.0000",
    text:"Payment to songwriter / composer as part of a publishing deal. Paid to songwriter/composer by publishing company."},
    {head:"Mechanical Royalties",
    rev:"$ 0.0000",
    text:"Royalties generated through the reproduction of recordings of your songs – either physical or digital. Paid to songwriter / composer by publisher, label, Harry Fox, or digital aggregator like CD Baby/TuneCore."},
    {head:"Commissions",
    rev:"$ 0.0000",
    text:"Typically a request from an ensemble, presenter, orchestra or other entity for a composer to create an original work for them."},
    {head:"Public Performance (PRO) Royalties",
    rev:"$ 0.0000",
    text:"Royalties generated when your songs are played on radio, TV, in clubs and restaurants. Paid to songwriter/composer/publisher by ASCAP/BMI/SESAC. "},
    {head:"Streaming Mechanical Royalties",
    rev:"$ 0.0000",
    text:"Royalties generated when your songs are streamed on on-demand services (Rhapsody, Spotify, Rdio). Paid to publisher by Harry Fox or other mechanical licensing agent. Publisher then pays songwriter/composer."},
    {head:"Composing Original Works for Broadcast",
    rev:"$ 0.0000",
    text:"Typically a commercial request to compose an *original* jingle, soundtrack, score, or other musical work for a film, TV or cable show, or an ad agency. Paid to songwriter/composer by agency requesting the work."},
   
    {head:"Synch Licenses",
    rev:"$ 0.0000",
    text:"Typically involves licensing an *existing* work for use in a movie, documentary, TV, video games, internet, or a commercial. Paid to songwriters/composers either via publisher or record label, or via a direct licensing deal with the licensee (movie studio, ad agency, etc) if you are self- published."},

    {head:"Sheet Music Sales",
    rev:"$ 0.0000",
    text:"Revenue generated by the sale or licensed reproduction of songs/compositions as sheet music. Paid to songwriter/composer by publisher, or directly from purchasers if you are selling it on your website or at performances."},

    {head:"Lyric Display",
    rev:"$ 0.0000",
    text:"Revenue generated by the licensed display of song lyrics. Online lyric sites pay publishers, which then pay songwriter/composer."},

    {head:"Ringtones",
    rev:"$ 0.0000",
    text:"Revenue generated from licensing your songs/compositions for use as ringtones. Paid to songwriter/composer via your publisher, your label or Harry Fox."},

    {head:"Songwriter Awards Programs",
    rev:"$ 0.0000",
    text:"Awards given by ASCAP and BMI Foundations to writer members of any genre whose performances are primarily in venues outside of broadcast media."},

    {head:"Publisher Settlement",
    rev:"$ 0.0000",
    text:"Payment from publishers to writers for litigation settlements."},

    {head:"RECORDING ARTIST REVENUE",
   rev:"",
    text:""},

    {head:"Record Label Advance",
    rev:"$ 0.00000000",
    text:"Paid to recording artist as part of signing a deal."},


    {head:"Record Label Support",
    rev:"$ 0.00000000",
    text:"Money from label for recording or tour support."},

    {head:"Retail Sales",
    rev:"$ 0.00000000",
    text:"Revenue generated from selling physical recordings in retail stores or via mailorder. Paid to recording artist/performer by your label, or services like CD Baby or Bandcamp that help musicians sell physical product. "},

    {head:"Digital Sales",
    rev:"$ 0.00000000",
    text:"Revenue generated from selling recordings digitally/online as permanent downloads. Paid to recording artist/performer by your label, or digital aggregator like CD Baby or TuneCore, or directly from fans via services like Bandcamp. "},

    {head:"Sales at Shows ",
    rev:"$ 0.00000000",
    text:"Revenue generated from selling recordings at shows/live performances. Paid to recording artist/performer directly by fans. "},

    {head:"Interactive Service Payments ",
    rev:"$ 0.00000000",
    text:"Revenue generated when your recordings are streamed on on-demand services (Rhapsody, Spotify, Rdio). Paid to recording artist/performer by your label, or digital aggregator like CD Baby or TuneCore."},

    {head:"Digital Performance Royalties ",
    rev:"$ 0.00000000",
    text:"Revenue generated when your sound recordings are played on internet radio, Sirius XM, Pandora. Paid to performers by SoundExchange."},

    {head:"Master Use Synch Licenses",
    rev:"$ 0.00000000",
    text:"Typically involves licensing an *existing* sound recording for use in a movie, documentary, TV, video games, internet, or a commercial. License fee paid to record label and/or recording artist via a direct licensing deal with the licensee (movie studio, ad agency, etc)."},


    {head:"AARC Royalties",
    rev:"$ 0.00000000",
    text:"Collected for the foreign performance of your recordings."},

    {head:"Neighboring Rights Royalties",
    rev:"$ 0.00000000",
    text:"Payments to songwriter / composer as part of a publishing deal. Paid to songwriter/composer by publishing company. "},

    {head:"Film Musicians Secondary Markets Fund",
    rev:"$ 0.00000000",
    text:"Paid to performers on recordings used in film, TV and other secondary uses by the Film Musicians’ Secondary Markets Fund."},

    {head:"Sound Recording Special Payments Fund",
    rev:"$ 0.00000000",
    text:"Paid to performers for the sales of music recorded under AFM collective bargaining agreement by the Sound Recordings Special Payments Fund."},

    {head:"SAG-AFTRA Contingent Scale Payments",
    rev:"$ 0.00000000",
    text:"Paid to non-royalty artists when a recording hits certain sales plateaus."},

    {head:"Label Settlements",
    rev:"$ 0.00000000",
    text:"Payments from labels to recording artists for litigation settlements (MP3.com, Limewire)."},

    {head:"PERFORMANCE REVENUE ",
   rev:"",
    text:""},

    {head:"Salary as Member of Orchestra or Ensemble",
    rev:"$ 0.00000000",
    text:"Income earned as a salaried member of an orchestra band, or ensemble."},

    {head:"Shows/Performance Fees",
    rev:"$ 0.00000000",
    text:"Revenue generated from playing in a live setting (for non-salaried players). Paid by concert promoter, presenter or venue to performer."},

    {head:"Session Musician/Sideman Fees for Studio Work",
    rev:"$ 0.00000000",
    text:"Payments to studio musicians/freelancers/"},

    {head:"Session Musician/Sideman Fees for Live Work",
    rev:"$ 0.00000000",
    text:"Payments to studio musicians/freelancers/sideman for work in a live setting/on tour. Paid by label, producer or artist, depending on situation."},

    {head:"Non-Featured Artist Payments",
    rev:"$ 0.00000000",
    text:"Payments from the AFM & SAG-AFTRA Intellectual Property Rights Distribution Fund, which distributes recording and performance royalties to non-featured artists."},


    {head:"TEACHING & PRODUCING",
   rev:"",
    text:""},

    {head:"Producer",
    rev:"$ 0.00000000",
    text:"Revenue generated from teaching your musical craft."},

    {head:"Music Teacher",
    rev:"$ 0.00000000",
    text:"Payment for producing another artists’ work in the studio or in a live setting. Paid by labels, featured artists, studios, presenters, or foundations, depending on situation."},

    {head:"Honoraria or Speakers’ Fees",
    rev:"$ 0.00000000",
    text:"Payment for conducting a lecture, workshop or master class. Usually paid by school, conservatory, or presenting organization."},


    {head:"BRAND RELATED REVENUE ",
   rev:"",
    text:""},


    {head:"Merchandise Sales",
    rev:"$ 0.00000000",
    text:"Revenue generated from selling branded merchandise (t-shirts, hoodies, posters, etc.). Paid to artist/performer by fans."},

    {head:"Fan Club",
    rev:"$ 0.00000000",
    text:"Money directly from fans who are subscribing to your fan club."},

    {head:"YouTube Partner Program",
    rev:"$ 0.00000000",
    text:"Shared advertising revenue, paid to partners by YouTube."},

    {head:"Ad Revenue ",
    rev:"$ 0.00000000",
    text:"Miscellaneous income generated by your website properties (click-thrus, commissions on Amazon sales, etc.)"},

    {head:"Persona Licensing",
    rev:"$ 0.00000000",
    text:"Payments from a brand that is licensing your name or likeness (video games, comic books)."},


    {head:"Product Endorsements ",
    rev:"$ 0.00000000",
    text:"Payments or free goods from a brand for you endorsing or using their product."},

    {head:"Acting ",
    rev:"$ 0.00000000",
    text:"Payments for appearances in TV, commercials, movies."},

    {head:"FAN, CORPORATE AND FOUNDATION FUNDING and OTHER SOURCES OF REVENUE",
    rev:" ",
    text:""},

    {head:"Fan Funding ",
    rev:"$ 0.00000000",
    text:"Money directly from fans to support or pre-sell an upcoming recording project or tour (Kickstarter, Pledge Music, IndieGogo)."},


    {head:"Sponsorship",
    rev:"$ 0.00000000",
    text:"Corporate support for a tour, or for your band/ensemble."},


    {head:"Grants",
    rev:"$ 0.00000000",
    text:"Foundation or public arts grants to support your work/project from foundations, state or federal agencies."},

    {head:"Arts Administrator",
    rev:"$ 0.00000000",
    text:"Money paid to you specifically for managing the administrative aspects of a group that you are a member of."},



];

    return(
        <div className="p-3">
         <div className="flex justify-between">
            <h1 className="font-bold lg:text-4xl">Total Revenue Generated</h1>
            <h1 className="font-bold lg:text-4xl">$ 10,000,567.85</h1>
         </div>
         <br />
         <br />
         <h2 className="font-bold lg:text-3xl">SONG WRITING &amp; COMPOSING REVENUE</h2>
         <br />
         <br />
         
            {
                arraylist.map((value,key)=>{
                    return(
                     <div key={key}>
                    <div className="flex justify-between">
                                <h3 className="w-[60%] font-bold lg:text-2xl">{value.head}</h3>
                                <h3 className="font-bol lg:text-2xl"> {value.rev}</h3>
                            </div>
                            <p>
                                {value.text}
                            </p>
                            <br />
                     </div>
                    )
                })
            }
       
         </div>
       


        
    )
}